################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_block_allocate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_block_pool_cleanup.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_block_pool_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_block_pool_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_block_pool_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_block_pool_initialize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_block_pool_prioritize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_block_release.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_byte_allocate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_byte_pool_cleanup.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_byte_pool_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_byte_pool_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_byte_pool_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_byte_pool_initialize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_byte_pool_prioritize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_byte_pool_search.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_byte_release.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_event_flags_cleanup.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_event_flags_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_event_flags_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_event_flags_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_event_flags_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_event_flags_initialize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_event_flags_set.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_event_flags_set_notify.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_initialize_high_level.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_initialize_kernel_enter.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_initialize_kernel_setup.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_mutex_cleanup.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_mutex_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_mutex_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_mutex_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_mutex_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_mutex_initialize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_mutex_prioritize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_mutex_priority_change.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_mutex_put.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_queue_cleanup.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_queue_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_queue_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_queue_flush.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_queue_front_send.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_queue_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_queue_initialize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_queue_prioritize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_queue_receive.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_queue_send.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_queue_send_notify.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_semaphore_ceiling_put.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_semaphore_cleanup.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_semaphore_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_semaphore_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_semaphore_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_semaphore_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_semaphore_initialize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_semaphore_prioritize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_semaphore_put.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_semaphore_put_notify.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_entry_exit_notify.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_identify.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_initialize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_preemption_change.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_priority_change.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_relinquish.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_reset.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_resume.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_shell_entry.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_sleep.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_stack_analyze.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_stack_error_handler.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_stack_error_notify.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_suspend.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_system_preempt_check.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_system_resume.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_system_suspend.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_terminate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_time_slice.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_time_slice_change.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_timeout.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_thread_wait_abort.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_time_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_time_set.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_timer_activate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_timer_change.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_timer_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_timer_deactivate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_timer_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_timer_expiration_process.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_timer_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_timer_initialize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_timer_system_activate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_timer_system_deactivate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/tx_timer_thread_entry.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_block_allocate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_block_pool_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_block_pool_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_block_pool_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_block_pool_prioritize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_block_release.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_byte_allocate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_byte_pool_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_byte_pool_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_byte_pool_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_byte_pool_prioritize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_byte_release.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_event_flags_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_event_flags_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_event_flags_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_event_flags_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_event_flags_set.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_event_flags_set_notify.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_mutex_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_mutex_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_mutex_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_mutex_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_mutex_prioritize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_mutex_put.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_queue_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_queue_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_queue_flush.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_queue_front_send.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_queue_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_queue_prioritize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_queue_receive.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_queue_send.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_queue_send_notify.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_semaphore_ceiling_put.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_semaphore_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_semaphore_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_semaphore_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_semaphore_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_semaphore_prioritize.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_semaphore_put.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_semaphore_put_notify.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_entry_exit_notify.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_info_get.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_preemption_change.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_priority_change.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_relinquish.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_reset.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_resume.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_suspend.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_terminate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_time_slice_change.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_thread_wait_abort.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_timer_activate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_timer_change.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_timer_create.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_timer_deactivate.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_timer_delete.o \
../Middlewares/ST/Debug/Middlewares/ST/threadx/common/src/txe_timer_info_get.o 


# Each subdirectory must supply rules for building sources it contributes

